<?php
include_once "Register.php";
//include_once "../Token.php";
/**
 * Created by PhpStorm.
 * User: 徐炜杰
 * Date: 2017/5/15
 * Time: 22:43
 */
class User_Register extends Register {

    function __construct($data){
        parent::__construct($data);
        $this->load->model('Index_Model');
    }

    function isRegister(){
        $result=parent::isRegister(); // TODO: Change the autogenerated stub
        if(!$result['state'])
            return $result;

        //check the phone
        //is empty
        if(empty($this->data['phoneNum'])){
            $result['state']=false;
            $result['errorMessage']="电话号码不得为空!";
            return $result;
        }
        //is the right format
        if(!preg_match("/^1[34578]\d{9}$/", $this->data['phoneNum'])){
            $result['state']=false;
            $result['errorMessage']="电话号码格式错误!";
            return $result;
        }

        //have been register
        if($this->Index_Model->isTeleUnique($this->data)){
            $result['state']=false;
            $result['errorMessage']="该号码已被注册!";
            return $result;
        }
        if(!$this->Index_Model->register($this->data)){
            $result['state']=false;
            $result['errorMessage']="注册失败请重试!";
            return $result;
        }
        //$result['token']=Token::encrypted($this->data);
        $result['state']=true;
        return $result;

    }
}